services: 
  - name: geth1
    description: this service runs the go-ethereum client
    image: "ethereum/client-go:alltools-latest" 
    volumes:
      - path: /staticpeers/
        name: staticpeers
        scope: singleton
    script:
      inline: cp /staticpeers/static-nodes.json /geth/geth/static-nodes.json && geth --nousb --datadir ./geth/ init /geth/genesis.json && geth --datadir ./geth/ --rpc --nodiscover --rpcaddr 0.0.0.0 --miner.gasprice=1 --rpcapi "admin,web3,db,eth,net,personal,miner,txpool" --rpccorsdomain "0.0.0.0" --txpool.nolocals --rpcvhosts=* --port 30303 --networkid 555555 --nousb --etherbase 0 --unlock 0 --allow-insecure-unlock --password ./geth/pw.txt --mine --minerthreads=1 --ethstats $NAME:secret@splunk.whiteblock.io:9002
    input-files: 
      - source-path: ./genesis.json
        destination-path: /geth/genesis.json
      - source-path: ./keystore/pk1
        destination-path: /geth/keystore/pk
      - source-path: ./keystore/pw.txt
        destination-path: /geth/pw.txt
      - source-path: ./keystore/nodekey1
        destination-path: /geth/geth/nodekey
    resources:
      cpus: 8
      memory: 8 GB
      storage: 30 GiB
  - name: geth2 
    description: this service runs the go-ethereum client
    image: "ethereum/client-go:alltools-latest"
    volumes:
      - path: /staticpeers/
        name: staticpeers
        scope: singleton
    script: 
      inline: cp /staticpeers/static-nodes.json /geth/geth/static-nodes.json && geth --nousb --datadir ./geth/ init /geth/genesis.json && geth --datadir ./geth/ --rpc --nodiscover --rpcaddr 0.0.0.0 --miner.gasprice=1 --rpcapi "admin,web3,db,eth,net,personal,miner,txpool" --rpccorsdomain "0.0.0.0" --txpool.nolocals --rpcvhosts=* --port 30303 --networkid 555555 --nousb --etherbase 0 --unlock 0 --allow-insecure-unlock --password ./geth/pw.txt --mine --minerthreads=1 --ethstats $NAME:secret@splunk.whiteblock.io:9002
    input-files: 
      - source-path: ./genesis.json
        destination-path: /geth/genesis.json
      - source-path: ./keystore/pk2
        destination-path: /geth/keystore/pk
      - source-path: ./keystore/pw.txt
        destination-path: /geth/pw.txt
      - source-path: ./keystore/nodekey2
        destination-path: /geth/geth/nodekey
    resources:
      cpus: 8
      memory: 8 GB
      storage: 30 GiB

sidecars:
  - name: splunk
    sidecar-to:
      - geth1
      - geth2
    image: gcr.io/whiteblock/splunk:latest
    resources:
      cpus: 2
      memory: 4 GB
      storage: 30 GiB
    script:
      inline:
        ethlogger --eth-rpc-url=http://$SERVICE:8545
    environment:
      NETWORK_NAME: whiteblock
      START_AT_BLOCK: latest
      SPLUNK_HEC_URL: "https://splunk.whiteblock.io:8088"
      SPLUNK_HEC_TOKEN: "f57efd39-f84d-470d-ae0e-ff0f67ee98c7"
      SPLUNK_EVENTS_INDEX: main
      SPLUNK_METRICS_INDEX: metrics
      SPLUNK_INTERNAL_INDEX: metrics
      SPLUNK_HEC_REJECT_INVALID_CERTS: "false"

task-runners:
  - name: wait
    script:
      inline: sleep 7200
  - name: geth-staticpeers-helper
    description: will gather the IP addresses and generate a static peers file.
    image: "gcr.io/whiteblock/helpers/besu/staticpeers:master"
    volumes:
      - path: /staticpeers/
        name: staticpeers
        scope: singleton
    script: 
      inline: ./besuStaticPeers generate -a '[{"publicKey":"04eab89943b5b2aa38745051471b31dc09d187c99b8fc6b740a8587ac43d1d65d644086a862189bc6298198453ba68076ebdb9cd7013d8893878f628a664376e"},{"publicKey":"a1ae7b1352fc0e02df6d75e90046d17fb212629a608f584760434df2375fb301ec9e55ac693a77f4bc0c3efdafec3b3853aa7cb2cb48480800ef6658f747d034"}]' -i '["'$GETH1_SERVICE0_COMMON_NETWORK'","'$GETH2_SERVICE0_COMMON_NETWORK'"]' >> /staticpeers/static-nodes.json
    resources: 
      cpus: 1
      memory: 2 GB
      storage: 5 GiB
tests: 
  - name: geth_network_2_nodes 
    description: first test - run two geth nodes on the common-network
    phases:
      - name: create
        tasks: 
        - type: geth-staticpeers-helper
      - name: start
        description: start the remaining node(s)
        system: 
        - name: geth1 
          type: geth1 
          count: 1 
          port-mappings:
            - "8545:8545"
          resources: 
            networks: 
              - name: common-network
        - name: geth2 
          type: geth2 
          count: 1 
          port-mappings:
            - "8545:8545"
          resources: 
            networks: 
              - name: common-network
      - name: wait
        tasks: 
        - type: wait
          timeout: 7200s
